#!/bin/sh

RAW=$(nvidia-smi stats -i 0 -c 1 -d temp,gpuUtil,memUtil)

USAGE=$(echo "$RAW" | awk '/gpuUtil/{ printf "%d%", $NF; exit; }')
MEM=$(echo "$RAW" | awk '/memUtil/{ printf "%d%", $NF; exit; }')
TEMP=$(echo "$RAW" | awk '/temp/{ printf "%d°", $NF; exit; }')

echo -e " $USAGE - $MEM - $TEMP"
