#!/bin/sh

SOURCE="@DEFAULT_AUDIO_SOURCE@"

case $BLOCK_BUTTON in
  1) wpctl set-mute $SOURCE toggle ;;   # left click
  4) wpctl set-volume $SOURCE 10%+ ;;   # scroll up
  5) wpctl set-volume $SOURCE 10%- ;;   # scroll down
esac

# Pega info do microfone
INFO=$(wpctl get-volume $SOURCE)

# Extrai volume (0.00–1.00 → %)
SOUND_LEVEL=$(echo "$INFO" | awk '{printf "%d", $2 * 100}')

# Detecta mute
echo "$INFO" | grep -q MUTED && MUTED=1 || MUTED=0

if [ "$MUTED" = "1" ]; then
    ICON=""
else
    ICON=""
fi

printf " %s %3s%% \n" "$ICON" "$SOUND_LEVEL"
