#!/bin/sh

STATUS=1

on() {
	$(redshift -O 5500)
	STATUS=1
}

off() {
	$(redshift -x)
	STATUS=0
}

case $BLOCK_BUTTON in
  1) on ;;  # left click
  3) off ;; # right click
esac

if [ "$STATUS" = "1" ];then
	echo ""
else
	echo ""
fi
